### ISSUE TITLE
the output genotype contains none operation

### ISSUE THREAD

**Issue by MarkAlive** [NeroLoh/darts-tensorflow#2]
`genotype is Genotype(normal=[('max_pool_3x3', 0), ('none', 1), ('max_pool_3x3', 0), ('none', 1), ('max_pool_3x3', 0), ('avg_pool_3x3', 2), ('max_pool_3x3', 0), ('sep_conv_5x5', 4)], normal_concat=[2, 3, 4, 5], reduce=[('max_pool_3x3', 0), ('max_pool_3x3', 1), ('max_pool_3x3', 0), ('max_pool_3x3', 2), ('max_pool_3x3', 0), ('max_pool_3x3', 2), ('max_pool_3x3', 0), ('max_pool_3x3', 3)], reduce_concat=[2, 3, 4, 5])`

it happened when condition `np.argmax(value) == PRIMITIVES.index('none')` is True in get_genotype function.

https://github.com/NeroLoh/darts-tensorflow/blob/7fd74eb40421a0ebaf86e72d489fdc749e38321a/cnn/model_search.py#L100

**Comment by NeroLoh** [comment]
Already fixed. Please check the uptate

**Comment by MarkAlive** [comment]
It works.
