### ISSUE TITLE
The test_acc tends to fluctuate during each epoch

### ISSUE THREAD

**Issue by MarkAlive** [NeroLoh/darts-tensorflow#4]
Hi @NeroLoh, if I understand corretly, test_acc is calc based on a batch size of valid data and don't accumulate it to calc the average test_acc of the total valid data set. This would cause a flucuation.

https://github.com/NeroLoh/darts-tensorflow/blob/dfe14a3480b5ebedb7292c4373c249ae96bd1f6e/cnn/train_search.py#L118

**Comment by NeroLoh** [comment]
Thanks. I have updated the code, please check
